name: productionai
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - random
  - glob
  - time
  - scipy
  - sklearn
  - simpy
  - openpyxl
  - pygad
  - basyx
  - seaborn
  - ultralytics
  - os
  - torch
  - label-studio
