name: productionai
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - scipy
  - sklearn
  - simpy
  - openpyxl
  - pygad
  - basyx
  - seaborn
  - statsmodels
  - shap
  - xgboost
  - tensorflow
